import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { toast } from "sonner";
import { ParallelForm } from "@/components/ParallelForm";
import { TimelineResults } from "@/components/TimelineResults";
import { generateParallelUniverses, type ParallelInput, type ParallelResult } from "@/lib/parallel.functions";
import { Sparkles } from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Parallel Universe — Explore your 'What if' dreams" },
      { name: "description", content: "An open-ended life simulator. Type your own 'What if' questions and AI generates 3 personalized parallel-universe timelines." },
      { property: "og:title", content: "Parallel Universe — Explore your 'What if' dreams" },
      { property: "og:description", content: "Your own dreams. Your own timelines. Generated by AI." },
    ],
  }),
  component: Index,
});

function Index() {
  const generate = useServerFn(generateParallelUniverses);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<ParallelResult | null>(null);
  const [name, setName] = useState("");
  const [started, setStarted] = useState(false);

  const onSubmit = async (d: ParallelInput) => {
    setLoading(true);
    setName(d.name);
    try {
      const r = await generate({ data: d });
      if (!r?.timelines?.length) throw new Error("No timelines returned");
      setResult(r);
      window.scrollTo({ top: 0, behavior: "smooth" });
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to generate universes");
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="min-h-screen px-4 py-10 md:py-16">
      {result ? (
        <TimelineResults result={result} name={name} onReset={() => { setResult(null); setStarted(false); }} />
      ) : started ? (
        <ParallelForm onSubmit={onSubmit} loading={loading} />
      ) : (
        <Landing onStart={() => setStarted(true)} />
      )}
    </main>
  );
}

function Landing({ onStart }: { onStart: () => void }) {
  return (
    <div className="max-w-4xl mx-auto text-center pt-12 md:pt-24 space-y-10">
      <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border bg-card-glass text-xs uppercase tracking-[0.2em] text-primary">
        <Sparkles className="size-3" /> Parallel Universe
      </div>
      <h1 className="text-5xl md:text-7xl font-bold tracking-tight leading-[1.05]">
        What if you lived <br/>
        <span className="text-gradient">a different life?</span>
      </h1>
      <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto">
        Type your own "What if" questions. AI reads your profile, your dreams, your constraints — and generates three personalized parallel-universe timelines from your current age to 80.
      </p>
      <div className="flex flex-col sm:flex-row items-center justify-center gap-3 pt-4">
        <button
          onClick={onStart}
          className="bg-gradient-cosmic text-primary-foreground rounded-full px-8 py-4 font-semibold shadow-glow hover:scale-[1.02] transition"
        >
          Explore my universes →
        </button>
        <span className="text-xs text-muted-foreground">Takes ~3 minutes · No signup</span>
      </div>

      <div className="grid md:grid-cols-3 gap-4 pt-12 text-left">
        {[
          { q: "What if I become the first billionaire of my bloodline?", t: "Legacy dream" },
          { q: "What if I start a company that changes my village?", t: "Impact dream" },
          { q: "What if I write a book that wins the Nobel Prize?", t: "Creative dream" },
        ].map((x, i) => (
          <div key={i} className="bg-card-glass border rounded-2xl p-5 animate-float" style={{ animationDelay: `${i * 0.4}s` }}>
            <div className="text-xs uppercase tracking-wider text-primary mb-2">{x.t}</div>
            <p className="text-base">{x.q}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
